#!/usr/bin/env bash

set -euo pipefail

# Extracts CMake Tools settings from a VSCode configuration files for use with command-line CMake

PROJECT_ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )

# By default, we use the settings specified for the `default` devcontainer
VSCODE_SETTINGS_ROOT=${VSCODE_SETTINGS_ROOT:-$PROJECT_ROOT/.devcontainer/default/VSCode}

case "$1" in
  "print-configure-args")
    shift 1 # Remove "print-configure-args" from the arguments

    if [[ $# -ne 0 ]]; then
      echo "Usage: $0 print-configure-args"
      echo "  Prints the arguments that would be passed to CMake."
      echo "  Takes no arguments."
      exit 1;
    fi

    VSCODE_SETTINGS_FILE=${VSCODE_SETTINGS_FILE:-"$VSCODE_SETTINGS_ROOT/settings.json"}
    if ! sed 's@//.*@@' < "$VSCODE_SETTINGS_FILE" | jq . > /dev/null; then
      echo "Error: $VSCODE_SETTINGS_FILE is not a valid JSON file."
      exit 1
    fi
    
    sed 's@//.*@@' < "$VSCODE_SETTINGS_FILE" | \
      sed "s@\${[A-Za-z]*orkspaceFolder}@$PROJECT_ROOT@" | \
      jq -jr '"\"\(.["cmake.configureArgs"] | join("\"\n\""))\"\n-S\(.["cmake.sourceDirectory"])\n-G \(.["cmake.generator"])\n"'

    ;;
  "print-build-targets"|"print-test-targets")
    TASK_KIND_TEMPORARY=${1#print-}
    TASK_KIND=${TASK_KIND_TEMPORARY%-targets}
    shift 1 # Remove command from the arguments

    if [[ $# -ne 0 ]]; then
      echo "Usage: $0 print-[build,test]-targets"
      echo "  Prints the targets specified for the default build or test task in tasks.json."
      exit 1;
    fi

    VSCODE_TASKS_JSON=${VSCODE_TASKS_JSON:-"$VSCODE_SETTINGS_ROOT/tasks.json"}
    if ! jq . < "$VSCODE_TASKS_JSON" > /dev/null; then
      echo "Error: $VSCODE_TASKS_JSON is not a valid JSON file."
      exit 1
    fi
    
    jq -r "[.tasks[] | select(.group | .kind == \"$TASK_KIND\" and .isDefault)][0] | .targets | join(\"\n\")" < "$VSCODE_TASKS_JSON"
    ;;
  *)
    echo "Usage: $0 [print-configure-args,print-build-targets,print-test-targets]"
    exit 1
    ;;
esac
