#!/usr/bin/env bash

set -euo pipefail

# Calls CMake, loading arguments from devcontainer settings to maintain a single source of truth.

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)

CMAKE_HELPER_BUILD_ROOT=${CMAKE_HELPER_BUILD_ROOT:-$PROJECT_ROOT/build}
CMAKE_HELPER_BUILD_DIR=${CMAKE_HELPER_BUILD_DIR:-$CMAKE_HELPER_BUILD_ROOT/$(basename "$PROJECT_ROOT")}

case "$1" in
  "print-configure-args")
    shift 1 # Remove "print-configure-args" from the arguments

    if [[ $# -ne 0 ]]; then
      echo "Usage: $0 print-configure-args"
      echo "  Prints the arguments that would be passed to CMake."
      echo "  Takes no arguments."
      exit 1;
    fi

    VSCODE_SETTINGS_FILE=${VSCODE_SETTINGS_FILE:-$PROJECT_ROOT/.devcontainer/default/VSCode/settings.json}
    if ! sed 's@//.*@@' < "$VSCODE_SETTINGS_FILE" | jq . > /dev/null; then
      echo "Error: $VSCODE_SETTINGS_FILE is not a valid JSON file."
      exit 1
    fi
    
    sed 's@//.*@@' < "$VSCODE_SETTINGS_FILE" | \
      sed "s@\${[A-Za-z]*orkspaceFolder}@$PROJECT_ROOT@" | \
      jq -jr '"\"\(.["cmake.configureArgs"] | join("\"\n\""))\"\n-S\(.["cmake.sourceDirectory"])\n-G \(.["cmake.generator"])\n"'
    echo "\"-DCMAKE_BUILD_TYPE=Debug\""
    echo "$@"

    ;;
  "configure")
    shift 1 # Remove "configure" from the arguments

    "${BASH_SOURCE[0]}" print-configure-args | xargs cmake \
      "-B$CMAKE_HELPER_BUILD_DIR" \
      "$@"
    rm -f "$PROJECT_ROOT/build/compile_commands.json"
    ln -s "$CMAKE_HELPER_BUILD_DIR/compile_commands.json" "$PROJECT_ROOT/build/compile_commands.json"
    ;;
  "build"|"test")
    TASK_KIND=$1
    shift 1 # Remove "build" or "test" from the arguments

    if [[ $# -eq 0 ]]; then
      TASKS_JSON=".vscode/tasks.json"
      if ! jq . < "$PROJECT_ROOT/$TASKS_JSON" > /dev/null; then
        echo "Error: $TASKS_JSON is not a valid JSON file."
        exit 1
      fi
      while IFS="=" read -r next; do
        TARGETS+=("$next")
      done < <(jq -r "[.tasks[] | select(.group | .kind == \"$TASK_KIND\" and .isDefault)][0] | .targets | join(\"\n\")" < "$PROJECT_ROOT/$TASKS_JSON")
    else
      TARGETS=("$@")
    fi

    set -x
    cmake \
      --build "$CMAKE_HELPER_BUILD_DIR" \
      --target "${TARGETS[@]}"
    ;;
  "install-with-dependencies")
    shift

    CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX:-$CMAKE_HELPER_BUILD_ROOT/install}

    if [[ $# -ne 1 ]]; then
      echo "Usage: cmake-helper install-with-dependencies"
      echo "  Installs the specified target and its dependencies"
    fi
    ROOT_TARGET="$1"

    #
    # GraphViz Options
    mkdir -p "$CMAKE_HELPER_BUILD_DIR"
    cat << EOF > "$CMAKE_HELPER_BUILD_DIR/CMakeGraphVizOptions.cmake"
set(GRAPHVIZ_EXECUTABLES OFF)
set(GRAPHVIZ_STATIC_LIBS ON)
set(GRAPHVIZ_SHARED_LIBS OFF)
set(GRAPHVIZ_MODULE_LIBS ON)
set(GRAPHVIZ_OBJECT_LIBS OFF)
set(GRAPHVIZ_GENERATE_DEPENDERS OFF)
set(GRAPHVIZ_EXTERNAL_LIBS OFF)
set(GRAPHVIZ_IGNORE_TARGETS "")
EOF

    #
    # Export GraphViz
    GRAPHVIZ_BASE="$CMAKE_HELPER_BUILD_ROOT/graphviz/dot"
    ./.devcontainer/cmake-helper print-configure-args | xargs cmake \
      "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}" \
      -B"$CMAKE_HELPER_BUILD_DIR" \
      --graphviz="$GRAPHVIZ_BASE"

    INSTALLED_LIBS_FILE="${CMAKE_INSTALL_PREFIX}/installed-libs.txt"

    # Install Libraries and Headers
    sed -n 's@^.* // .* -> \(.*\)@\1@p' < "$GRAPHVIZ_BASE.$ROOT_TARGET" |
      sort -u > "$INSTALLED_LIBS_FILE"
    xargs cmake \
        --build "$CMAKE_HELPER_BUILD_DIR" \
        --target install-{llvm,mlir,circt}-headers < "$INSTALLED_LIBS_FILE"

    # Create pkg-config file
    PKG_CONFIG_DIR="$CMAKE_INSTALL_PREFIX/lib/pkgconfig"
    mkdir -p "$PKG_CONFIG_DIR"
    cat << EOF > "$PKG_CONFIG_DIR/${ROOT_TARGET}.pc"
Name: ${ROOT_TARGET}
CFlags: -I${CMAKE_INSTALL_PREFIX}/include
Libs: -L${CMAKE_INSTALL_PREFIX}/lib $(sed 's/^/-l/' < "$INSTALLED_LIBS_FILE" | tr '\n' ' ')
EOF
    ;;
  *)
    echo "Usage: $0 [configure|build|test]"
    exit 1
    ;;
esac
